// app/layout.js

import "./globals.css";
import './custom.css';
import Header from '@/components/Header';
import PageTransition from '@/components/PageTransition';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body className={`antialiased pt-0 font-pretendard`}>
        <PageTransition />
        <Header />
        {children}
      </body>
    </html>
  );
}